# -*- coding: utf-8 -*-
"""api_gem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1as5gJylxksxXe36KDetheEAwpzpetS4n
"""

import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown
# Used to securely store your API key
#from google.colab import userdata

def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

# Or use `os.getenv('GOOGLE_API_KEY')` to fetch an environment variable.
GOOGLE_API_KEY='AIzaSyAKv-x-Z5CofHdaWnHgugyfBNu5Oe7yUF4'

genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-1.5-flash')

response = model.generate_content("o que é a vida?")

to_markdown(response.text)